### PR TITLE
Added fix for storing nextBuildNumber

### PR DESCRIPTION
**Pull request by rahuldshetty**
**Problem:**
Jenkins backup script was only considering _*.xml files_ during the backup. This didn't include _nextBuildNumber file_ which is important if we want to maintain build numbers.

**Solution**:

- Find and add the _nextBuildNumber file_ while searching for all the _*.xml files_

### CODE REVIEW

**Comment by sue445** [comment]
Your patch is LGTM, but there is no test.

Can you add test case?

1. provision jenkins which including `nextBuildNumber` file
2. Add check to https://github.com/sue445/jenkins-backup-script/blob/master/spec/jenkins-backup_spec.rb whether `nextBuildNumber` file is included

**Comment by rahuldshetty** [comment]
Added the check for _nextBuildNumber_ file.

**Comment by sue445** [comment]
LGTM!

**Comment by sue445** [comment]
Released as `0.1.10` 🚀

**Pull request merged**
